CREATE DATABASE Tori;
USE Tori;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE postulaciones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombres VARCHAR(100) NOT NULL,
  apellidos VARCHAR(100) NOT NULL,
  edad INT NOT NULL CHECK (edad >= 18 AND edad <= 65),
  dni CHAR(8) NOT NULL UNIQUE,
  puesto VARCHAR(50) NOT NULL,
  fecha_postulacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);